In [1]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [5]:
x = iris.data
y = iris.target

In [6]:
x[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=111)

 ## scikit-learn StandardScaler

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
standardScaler = StandardScaler()

In [11]:
standardScaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
standardScaler.mean_

array([5.8125, 3.035 , 3.7125, 1.17  ])

In [17]:
# variance
standardScaler.var_

array([0.67026042, 0.18744167, 3.01192708, 0.54776667])

In [18]:
# std
standardScaler.scale_

array([0.81869434, 0.43294534, 1.73549044, 0.7401126 ])

In [19]:
standardScaler.transform(x_train)

array([[-1.48101672,  1.30501463, -1.56295876, -1.31061138],
       [-0.13741392, -0.08084161,  0.28090042,  0.04053437],
       [-1.48101672,  0.38111047, -1.33247637, -1.31061138],
       [-0.50385105,  1.99794275, -1.39009697, -1.04038223],
       [ 1.08404317,  0.15013443,  0.39614162,  0.31076352],
       [ 1.08404317, -0.08084161,  0.85710642,  1.5267947 ],
       [ 1.572626  , -0.08084161,  1.26045062,  1.25656555],
       [-0.01526821, -0.77376973,  0.22327982, -0.22969478],
       [-1.72530814, -0.31181765, -1.33247637, -1.31061138],
       [-0.38170534, -1.69767389,  0.16565922,  0.17564895],
       [-0.99243388, -2.39060201, -0.12244377, -0.22969478],
       [ 0.96189746, -0.31181765,  0.51138282,  0.17564895],
       [ 0.2290232 ,  0.84306255,  0.45376222,  0.58099267],
       [-0.13741392, -1.00474577, -0.12244377, -0.22969478],
       [ 1.69477171,  0.38111047,  1.31807122,  0.85122182],
       [-0.38170534, -1.00474577,  0.39614162,  0.04053437],
       [ 1.32833458,  0.

In [20]:
standardScaler.transform(x_test)

array([[-0.87028817,  0.84306255, -1.27485577, -1.31061138],
       [-0.99243388,  0.84306255, -1.21723517, -1.04038223],
       [ 1.69477171,  1.30501463,  1.37569182,  1.79702385],
       [ 0.59546033, -0.77376973,  0.68424462,  0.85122182],
       [ 1.08404317, -0.08084161,  0.74186522,  0.71610725],
       [-1.2367253 ,  0.84306255, -1.04437337, -1.31061138],
       [-0.87028817,  1.07403859, -1.33247637, -1.31061138],
       [ 1.32833458,  0.15013443,  0.97234762,  1.25656555],
       [ 1.08404317,  0.61208651,  1.14520942,  1.79702385],
       [ 0.59546033,  0.61208651,  0.56900342,  0.58099267],
       [ 2.54979167,  1.76696671,  1.54855361,  1.12145097],
       [-0.38170534,  1.07403859, -1.39009697, -1.31061138],
       [ 0.2290232 , -1.92864993,  0.74186522,  0.4458781 ],
       [ 1.08404317,  0.61208651,  1.14520942,  1.25656555],
       [ 2.18335454, -0.08084161,  1.66379481,  1.25656555],
       [-0.13741392,  3.15282295, -1.27485577, -1.04038223],
       [ 0.47331462, -0.

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [23]:
y_train

array([0, 1, 0, 0, 1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 1,
       2, 2, 1, 1, 2, 1, 2, 0, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 0, 1, 1,
       1, 1, 2, 2, 0, 1, 0, 1, 2, 2, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0,
       1, 2, 0, 0, 2, 0, 1, 1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 2,
       0, 0, 0, 0, 2, 1, 0, 1, 2, 1])

In [24]:
knn_clf.fit(standardScaler.transform(x_train), y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [25]:
knn_clf.score(standardScaler.transform(x_test), y_test)

0.9333333333333333